# Generated by Django 4.1.5 on 2023-01-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(choices=[('1000', '1000'), ('5000', '5000'), ('10000', '10000'), ('50000', '50000'), ('100000', '100000')], default='5000', max_length=64)),
                ('tenure', models.CharField(choices=[('6', '6 months'), ('12', '1 year'), ('18', '1.5 year'), ('24', '2 year'), ('36', '3 year'), ('42', '3.5 year'), ('48', '4 year')], default='12', max_length=64)),
                ('benefitPercentage', models.FloatField(default=0)),
                ('benefitType', models.CharField(choices=[('cashback', 'cashback'), ('extraVoucher', 'extraVoucher')], default='cashback', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
