# Generated by Django 4.1.5 on 2023-01-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_customergoals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerGoals',
            new_name='CustomerGoal',
        ),
    ]
