# Generated by Django 4.1.5 on 2023-01-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_rename_customergoals_customergoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tenure',
        ),
        migrations.AddField(
            model_name='plan',
            name='amountOptions',
            field=models.CharField(default='1000', max_length=512),
        ),
        migrations.AddField(
            model_name='plan',
            name='tenureOptions',
            field=models.CharField(default='12', max_length=512),
        ),
    ]
